"""empty message

Revision ID: 08b383326213
Revises: 333d292172e0
Create Date: 2019-07-27 14:05:52.646408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08b383326213'
down_revision = '333d292172e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('menu_item_number', mysql.INTEGER(display_width=10), autoincrement=False, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('price', mysql.DOUBLE(precision=3, scale=2, asdecimal=True), nullable=False),
    sa.Column('drinkstatus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('drink_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('drink_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('menu_item_number'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
