"""empty message

Revision ID: 335f7c465c2c
Revises: b111a20054b9
Create Date: 2019-07-29 20:47:44.489942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '335f7c465c2c'
down_revision = 'b111a20054b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.alter_column('drink_order', 'order_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('drink_order_ibfk_3', 'drink_order', type_='foreignkey')
    op.drop_constraint('drink_order_ibfk_1', 'drink_order', type_='foreignkey')
    op.drop_constraint('drink_order_ibfk_4', 'drink_order', type_='foreignkey')
    op.drop_column('drink_order', 'employee_id')
    op.drop_column('drink_order', 'total_price')
    op.drop_column('drink_order', 'menu_item_number')
    op.drop_column('drink_order', 'add_on_number')
    op.alter_column('order_item', 'add_on_number',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=False)
    op.alter_column('order_item', 'employee_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'employee_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=True)
    op.alter_column('order_item', 'add_on_number',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=True)
    op.add_column('drink_order', sa.Column('add_on_number', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True))
    op.add_column('drink_order', sa.Column('menu_item_number', mysql.INTEGER(display_width=10), autoincrement=False, nullable=False))
    op.add_column('drink_order', sa.Column('total_price', mysql.DOUBLE(precision=4, scale=2, asdecimal=True), nullable=True))
    op.add_column('drink_order', sa.Column('employee_id', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True))
    op.create_foreign_key('drink_order_ibfk_4', 'drink_order', 'add_on_item', ['add_on_number'], ['add_on_number'])
    op.create_foreign_key('drink_order_ibfk_1', 'drink_order', 'menu_item', ['menu_item_number'], ['menu_item_number'])
    op.create_foreign_key('drink_order_ibfk_3', 'drink_order', 'employee', ['employee_id'], ['employee_id'])
    op.alter_column('drink_order', 'order_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_table('customer',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('customer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
