"""empty message

Revision ID: 3bff9561d499
Revises: b0e4e8b840c6
Create Date: 2019-07-30 16:45:33.927467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bff9561d499'
down_revision = 'b0e4e8b840c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_add_on_item_food_description'), 'add_on_item', ['food_description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_add_on_item_food_description'), table_name='add_on_item')
    # ### end Alembic commands ###
