"""empty message

Revision ID: a2af8e556bac
Revises: 08b383326213
Create Date: 2019-07-27 14:15:25.513253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2af8e556bac'
down_revision = '08b383326213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('menu_item_number', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('drinkstatus', sa.Boolean(), nullable=True),
    sa.Column('drink_type', sa.String(length=128), nullable=True),
    sa.Column('drink_description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('menu_item_number')
    )
    op.create_index(op.f('ix_menu_item_item_name'), 'menu_item', ['item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_item_item_name'), table_name='menu_item')
    op.drop_table('menu_item')
    # ### end Alembic commands ###
