"""empty message

Revision ID: dc1f4accfff7
Revises: e148b7d4411c
Create Date: 2019-07-29 21:29:29.377289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc1f4accfff7'
down_revision = 'e148b7d4411c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'add_on_number',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_item', 'add_on_number',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=False)
    # ### end Alembic commands ###
