"""empty message

Revision ID: e148b7d4411c
Revises: 335f7c465c2c
Create Date: 2019-07-29 21:18:39.090425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e148b7d4411c'
down_revision = '335f7c465c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('menu_item_name', sa.String(length=128), nullable=False))
    op.create_foreign_key(None, 'order_item', 'menu_item', ['menu_item_name'], ['item_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'menu_item_name')
    # ### end Alembic commands ###
